#### Main entrypoint of the workflow ####


# It has been generated following the best practices available at
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 


##### set minimum snakemake version #####
# from snakemake.utils import min_version
# min_version("6.5.0")

#### load rules #####
include: "rules/common.smk"

#### Main target rule ####
rule all:    
    script:
	    "scripts/hello.py"
